### PR TITLE
Set up ChatClient, ChatServer, and ChatCommon

### PR DESCRIPTION
**Pull request by zhaolang05**

### CODE REVIEW

**Comment by Limelime1214** [comment]
The package structure is consistent with the clean architecture.

**Review by Limelime1214 — APPROVED** [review]
The package structure is perfectly consistent with clean architecture.

**Comment by KerryGu** [comment]
ok

**Review by KerryGu — APPROVED** [review]

**Comment by KerryGu** [comment]
Great work

**Comment by KerryGu** [comment]
fantastic

**Pull request merged**
